version: "3"
services:
  # API
  chat-server-1:
    build:
      context: .
      dockerfile: chat_server_1/chat_server1.Dockerfile
    image: chat_server/chat_server_1
    ports:
      - "8000:8000"
    command: sh -c "uvicorn source.main:app --host 0.0.0.0 --port 8000 --reload"

  chat-server2:
    build:
      context: .
      dockerfile: chat_server_2/chat_server2.Dockerfile
    image: chat_server/chat_server_2
    ports:
      - "8001:8001"
    command:  sh -c "uvicorn source.main:app --host 0.0.0.0 --port 8001 --reload"

# $ docker-compose up --build
